---
# tasks file for wordpress
- name: install wordpress
  unarchive:
     src: https://wordpress.org/latest.tar.gz
     dest: /var/www/html
     remote_src: yes
  become: yes

- name: update Apache site
  lineinfile:
     dest: /etc/apache2/sites-enabled/000-default.conf
     regexp: "(.)+DocumentRoot /var/www/html"
     line: "DocumentRoot /var/www/html/wordpress"
  notify: Restart Apache
  become: yes

- name: upload wp-config
  template:
     src: wp-config.php.j2
     dest: /var/www/html/wordpress/wp-config.php
  become: yes

- name: restart apache
  service: 
     name: apache2
     state: restarted
  become: yes
