---
# tasks file for wordpress
- name: install wordpress
  unarchive:
     src: https://wordpress.org/latest.tar.gz
     dest: /var/www/html
     remote_src: yes
  become: yes

- name: create wordpress db
  mysql_db:
     name: "{{ wordpress_db_name }}"
     state: present
     login_user: "{{ mysql_user_name }}"
     login_password: "{{ mysql_user_password  }}"
  become: yes

- name: upload wp-config
  template:
     src: wp-config.php.j2
     dest: "{{ wp_conf_file_dest }}"
  become: yes

- name: restart apache
  service:
     name: apache2
     state: restarted
  become: yes
